### PR TITLE
chore: adjust compat entry for Nemo and bump version

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by ederc** [comment]
@thofma Any ideas why the `julia v1.6` tests fail? Is the ` (f, NARGS) = (AlgebraicSolving.submul, 4)` output coming from the new Nemo version?

**Comment by thofma** [comment]
Hm, no clue. I will have a look tomorrow.

**Comment by thofma** [comment]
I just noticed that the documentation build pinned Nemo to 0.36.*, which is rather old. Let's see what happens now.

**Comment by thofma** [comment]
OK, I will have to adjust a few things tomorrow.

**Comment by ederc** [comment]
OK, thanks, let me know if I can help you tomorrow.

**Comment by thofma** [comment]
I think I got everything working now. But I just noticed something about the printing, which we should fix now in Nemo. So let's put this on hold for a moment.

**Comment by thofma** [comment]
Ignore my previous comment. I just had to add an export statement here. Everything should be good to go now. Sorry for the confusion.

**Pull request merged**
